### ISSUE TITLE
Everything is empty

### ISSUE THREAD

**Issue by iamLazyCode** [alvr/katana#248]
Hi sir why everything is empty
![Screenshot_20221129_151145_Katana Beta.jpg](https://user-images.githubusercontent.com/13099434/204494349-96c033f9-3761-4b2d-837f-2e3c88f73431.jpg)
![Screenshot_20221129_151141_Katana Beta.jpg](https://user-images.githubusercontent.com/13099434/204494362-684bb10d-4454-4e32-96e0-8a11a5ca693f.jpg)

**Comment by alvr** [comment]
Hello @ifelixculpa,

I work on this personal project in my spare time as a hobby to learn Compose and keeping updated with the latest Android related libraries and techology.

Right now the only usable things to do are the lists, but only simple things, no edition or entry information.

The next thing I will probably do is the explore screen, but no ETA.

**Comment by iamLazyCode** [comment]
> Hello @ifelixculpa,
> 
> I work on this personal project in my spare time as a hobby to learn Compose and keeping updated with the latest Android related libraries and techology.
> 
> Right now the only usable things to do are the lists, but only simple things, no edition or entry information.
> 
> The next thing I will probably do is the explore screen, but no ETA.

Il keep eye on the superb project sir thanks
